site_name: Polish Language Database
site_url: https://polishcc.github.io/polish-db/
site_dir: site
use_directory_urls: true

nav:
  - Polish Language Database: index.md
  - In English:
      - Polish fonetics: english/fonetics.md
  - En français:
      - Phonétique polonaise: french/phonetique.md

theme:
  name: material

extra_css:
  - stylesheets/extra.css